server:
  port: 8084
fastGpt:
  server: http://172.22.16.126:3000
  model: qwen2:7b
  maaSType: fastGpt
biSheng:
  server: http://172.22.16.127:3001
  model: 3
  maaSType: biSheng
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:uui}
    username: ${POSTGRES_USERNAME:uui}
    password: ${POSTGRES_PASSWORD:uui}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath*:llm-adaptation-init.sql
      mode: always
mybatis:
  configuration:
    database-id: PostgreSQL
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    org.springframework.web: DEBUG